pipeline {
    agent any

    parameters {
        gitParameter (  branch: '', 
                        branchFilter: 'origin/(.*)', 
                        defaultValue: 'main', 
                        description: '', 
                        name: 'BRANCH', 
                        quickFilterEnabled: true, 
                        selectedValue: 'TOP', 
                        sortMode: 'DESCENDING', 
                        tagFilter: '*', 
                        type: 'PT_BRANCH', 
                        useRepository: 'git@github.com:Samidarex/ADB.git')
             booleanParam(name: 'CLEAN_WORKSPACE', defaultValue: true, description: 'Clean')

             booleanParam(name: 'TESTING_FRONTEND', defaultValue: false, description: 'Front')
    }

    stages {
        stage('Dependency install') {
            steps {
                git 'https://github.com/Samidarex/ADB.git'
                bat 'npm install'
            }
        }
        stage('Test') {
            steps {
                script{
                if(TESTING_FRONTEND == true){
                echo "TESTING_FRONTEND = true"
                bat './jenkins/scripts/test.bat'
                } else
                echo "TESTING_FRONTEND = false"
                }
            }
               
            }
        }
        stage('Build') {
            steps {
                bat './jenkins/scripts/deliver.bat'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                bat './jenkins/scripts/kill.bat'
            }
            post
            {
                success{
               
                    bat 'git add .'
                    bat 'git commit -am "Updated version"'
                    input message: 'Commit created succesfully, starting clearing the workspace'
                    cleanWs deleteDirs: true, patterns: [[pattern: 'node_modules', type: 'EXCLUDE']]
                }
            }
        }
    }
}
