pipeline {
    agent any

    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                git 'https://github.com/Samidarex/ADB.git'
                bat 'npm install'
            }
        }
        stage('Test') {
            steps {
                bat 'bash ./jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                bat 'bash ./jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                bat 'bash ./jenkins/scripts/kill.sh'
            }
        }
    }
}
