pipeline {
    agent any

    parameters {
        gitParameter (  branch: '', 
                        branchFilter: 'origin/(.*)', 
                        defaultValue: 'main', 
                        description: '', 
                        name: 'BRANCH', 
                        quickFilterEnabled: true, 
                        selectedValue: 'TOP', 
                        sortMode: 'DESCENDING', 
                        tagFilter: '*', 
                        type: 'PT_BRANCH', 
                        useRepository: 'git@github.com:Samidarex/ADB.git')
    }

    stages {
        stage('Dependency install') {
            steps {
                git 'https://github.com/Samidarex/ADB.git'
                bat 'npm install'
            }
        }
        stage('Test') {
            steps {
                bat './jenkins/scripts/test.bat'
            }
        }
        stage('Build') {
            steps {
                bat './jenkins/scripts/deliver.bat'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                bat './jenkins/scripts/kill.bat'
            }
            post
            {
                success{
               
                    bat 'git add .'
                    bat 'git commit -am "Updated version"'
                    input message: 'Commit created succesfully!'
                }
            }
        }
    }
}
